### ISSUE TITLE
Do not generate qualifier edge if value is empty

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#149]
Do not generate kgtk edge if the qualifier value is empty.

For example, edges corresponding to I8, I10, and so on should not be generated.
![image](https://user-images.githubusercontent.com/1087657/89950582-c1de1080-dbde-11ea-8e56-1f46fb65b94f.png)

[edges-with-empty-qualifier-values.tar.gz](https://github.com/usc-isi-i2/t2wml/files/5059575/edges-with-empty-qualifier-values.tar.gz)

**Comment by devowit** [comment]
is having an empty cell somewhere a qualifier is defined considered an error (such that the cell is colored orange and the user gets a warning about errors in the input)? or should it simply silently remove the edge?

**Comment by devowit** [comment]
an initial resolution to this issue (treating empty cells as errors) is in usc-isi-i2/t2wml-api@e228b7fd9

**Comment by kyao** [comment]
This issue can be closed after the next release

**Comment by szeke** [comment]
I think this issue is related to the one about units, which is the handling of empty values. The general rule should be:

- if the value is empty, do not generate the corresponding edge or piece of info, eg unit or precision
- if the value is empty, and `warn about empty values` is True, the cell should be orange.

**Comment by devowit** [comment]
related to issue #153
