### ISSUE TITLE
Implement data cleaning part 1

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#159]
Implement data cleaning in the YAML file to support common data cleaning cases as specified in https://docs.google.com/document/d/1GMWGOYMGRi8Tfg7dWxjUOZKZt6KqtS15o2hWfcUCTiI/edit?usp=sharing

**Comment by devowit** [comment]
I'm going to compile my running list of questions on data cleaning here:

`remove_symbols`: 
1. for parenthesis argument is that literally just `( )` or also `[]{}`?
2. what do you mean by remove symbols but not unicode? can you give an example of a symbol not covered under punctuation that isn't unicode?
3. for punctuation, with argument "everywhere" are we including things like the decimal point in a number? or do we need to check not to remove that?

`remove_unicode`:
1. emoji are a constantly updating library. we need to decide how often we want to update the emoji definitions file.
2. this should leave punctuation etc untouched?

**Comment by devowit** [comment]
Comments from meeting September 22nd:
left/right have been changed to start/end
remove_symbols and remove_unicode have been dropped, in favor of `make_alphanumeric` and `make_ascii`
`remove_long` has been renamed to the clearer `truncate`

additional clarifications needed from meeting september 22nd:
- I still need an example of the smart behavior desired for pad with a non-divisible padding provided (ie `.-.-` and the padding length needed is 1 or 3)
- we decided we would not implement fix_url until @szeke has a chance to review common problems with URLs and sends them to me

**Comment by devowit** [comment]
discussion copied from slack, october 1st:

**description of plans for make_numeric:**

One: I will add a decimal argument, decimal="."  (with default values as indicated).  Decimal will be replaced with . and preserved when stripping non-numeric characters. I considered adding a separator character but realized we don't need one, because we're anyway stripping separators, spaces, and all non-numeric characters except "-", ".", and "e" for scientific notation

so 33.899,99€ will become 33899.99  and 33 000 000 will become 33000000

Two: Other than the decimal character converted to a period, the only other non-digit character that will be preserved is - in the beginning of a string. so -20 profits will  become -20, and 2-0 wins-losses will become 20 (obviously in the latter case you probably should not be using make_numeric but some other function)

Three: the make_numeric request asks for support for scientific notation as well. assuming you mean something like 8e10or 8E10, that's trivial to add (and will become 80000000000.0). If you mean something else, please let me know. (eg LaTeX formatting etc?)

Is this fine? It will not handle some complex numeric cases that I think you will need to add custom regex for.....

(How do we want to handle inappropriate input to make_numeric like Hello. World. which would become ..? Or, for that matter, 10.12.20? 10E10E10? I can, in general, add a check that the result of make_numeric is a valid number and if not raise an error that make_numeric failed...)

> szeke: This is fine. Latex support would be nice, eg, 8.0^2 becomes 8.0E2. For the bad cases with multiple dots, etc., if you apply the rules, and the result is not a number, then leave it unchanged.

**removal/replacement**

for remove_regex, I'm wondering if we should design it to match underlying python handling as closely as possible.
(python's re module has re.sub, which if you sub in an empty string is removing)
should we have sub_regex instead of remove_regex, and allow users to specify something other than an empty string if they want?
I'm still trying to understand what you (@szeke) mean by removing groups, "if there are groups, it removes all the groups." Do you mean, eg,  string: "Pedro oops Szekely", regex: (Pedro|oops) -> "Szekely"? (this is easy to do).  "Isaac Newton, physicist", regex "(\w+) (\w+) -> ", physicist", also easy. But I'm not sure how I'd do  string: "Pedro oops Szekely", regex: (Pedro)(Szekely) -> oops. (ie am i actually separatting out each group and looking for it separately? seems messy...)

Kind of a continuation of 2, kind of a question about remove_numbers and remove_letters (which are essentially just special cases of remove_regex we're separating for convenience):

Lets say the string is "Pedroops" and the list of strings to remove is ["Pedro", "oops"], the returned string will be "ops" is that fine?

(For numbers, I do a loop: so that if you submit a list [1, 12] it actually removes the 12s, it otherwise wouldn't. but problems like "312" remove "31, 12" would still remain. Actually the problem with doing it in a loop is that then for the number 1312 I'd end up removing the entire number. I need to think about this...)

Honestly looking over all of this I am inclined to say that remove_numbers should remove all numbers, remove_letters remove all letters, period.

No option for a list of letters or numbers to remove, once a user wants something that complicated they should use remove_regex, instead of me having to guess and figure out what they mean.

The regex will be treated literally as re.sub(regex, replacement="", input, count=0) (bolded are arguments user can provide, input will of course be cells from the spreadsheet), this means users can test regexes in normal regex testing areas like https://regex101.com/ to make sure they've written it to do what they intend instead of having to play trial and error with t2wml's custom interpretation, there won't be a where argument, instead user will make the regex as appropriate, ie add ^ or $ to fix to beginning or end of string themselves.

>szeke: good idea, sub is better than remove


**refactoring functions from existing t2wml to cleaning**

now that we are creating an entire set of cleaning functions, maybe it's time to rename the existing t2wml function clean (uses ftfy) to ftfy,  and add it to the cleaning functions (ie allow it to be used in t2wml yaml, which does not modify underlying data, but also allow it to be used in cleaning yaml, which modifies underlying data?

in fact a number of the string modifier yaml functions should maybe be moved and/or retired. do we need upper/lower/title when we're adding change_case? same for strip, which is just the default behavior for strip_whitespace. depending on what we decide for remove_regex (ie whether we want it to be replace_regex, instead), maybe also replace ?

again, all clean functions can be used in the usual yaml to change output without changing underlying displayed data, or can be used in the cleaning yaml to create a new copy of the data, cleaned. so it doesn't make sense to have any overlapping functionality.

**Comment by devowit** [comment]
additional questions:
for remove_letters, what do we want NOT removed? numbers, i assume, but what about smilies, punctuation, symbols, etc? is remove_letters equivalent to the inverse of remove_numbers, ie leave only numbers? or something else?

can we use a GPL licensed package for make_ascii?

**Comment by zmbq** [comment]
Using GPL requires our license to be GPL too. I don’t think they allow more relaxed licenses. I think we should avoid GPL packages as much as we can.

**Comment by devowit** [comment]
so anyone who `pip install`s a GPL package has now made any package with that dependency or with a dependency on their package GPL?

**Comment by szeke** [comment]
I looked into the license further, and we CANNOT use the GPL library. @devowit you are correct, linking against the GPL library forces the entire code to acquire the GPL license. So we should not use Unidecode.

**Comment by devowit** [comment]
I am splitting this issue into two parts. This issue is for the cleaning functions themselves, and the second issue is for creating a cleaned copy of the data file, displaying it in the UI, etc.

**Comment by devowit** [comment]
this and it's related issues have been released in 2.3.9. 
bugs or new feature requests should be opened as new issues
