### ISSUE TITLE
T2WML should not allow multiple projects with same directory

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#167]
This is in branch `annotation-integration` which has the latest code from `development`, synced today morning
![image](https://user-images.githubusercontent.com/6811931/90463764-98325700-e0c0-11ea-99d3-11fc8b3874ee.png)

**Comment by saggu** [comment]
Still an issue in 2.3.3

**Comment by saggu** [comment]
The way to achieve this in 2.3.3 is as follows:
1. Create a folder in /tmp and call it test6 and use this to create a new project
2. A new project is created with name test6
3. Create a folder in /tmp/test6 and call in test6, use this to create a new project
4. See 2 projects with same name: test6

**Comment by zmbq** [comment]
I think we should drop the project name concept entirely. I suggest we use the project path (which is unique), and also add a project description you can edit - the description will help you remember what the project is about, but the path is the real identifier of the project.

Anyway, since we're using the local file system now, you can always take a project and copy it to another directory. t2wml needs to be able to handle that in a non-confusing way.

**Comment by devowit** [comment]
Ok. Despite it being visible in the demo last night, I have not been able to replicate the repeated directory bug. I think it might have been an artefact of a corrupted database (ie one that already had two projects with same path present when I added the code to prevent that from happening). I'm sticking this in ready for testing.

**Comment by saggu** [comment]
Creating a new project in a folder which already has a T2WML project, notifies the user and does not create a new project. Since we are allowing duplicate project names, this issue is now closed.
