### ISSUE TITLE
Save yaml even if it is invalid

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#179]
We are developing a fill-in-the-blank tutorial for t2wml. The yaml has value parts missing, and the user is supposed to fill in the missing parts. But, t2wml does not save the yaml if it has errors.

**Comment by kyao** [comment]
Also, I tried uploading a correct yaml, then modifying it to add in the blank. Then I get this error and I can no longer switch back to the sheet:

![image](https://user-images.githubusercontent.com/1087657/90698021-9ab5bd80-e234-11ea-9c63-efd1b08ff819.png)

**Comment by devowit** [comment]
There are two kinds of invalid yamls:

1. invalid by yaml standards, ie has a `key:` and no value provided for the key, pyyaml would not be able to parse it at all.
2. invalid by t2wml standards, ie has keys that we don't allow, is missing required keys, etc.

do you want to allow both kinds to be saved, or only the latter? because currently for the former we don't even send it to the backend at all...

**Comment by kyao** [comment]
Handling case 2 invalid by t2wml standards would be good enough

**Comment by devowit** [comment]
version 2.2.0
