### ISSUE TITLE
Load Project related issues

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#180]
1. Cannot load project with the error below:

![image](https://user-images.githubusercontent.com/1087657/90710048-68b35400-e252-11ea-9a56-873c5667ebec.png)

I am not sure why multiple yaml per sheet are kept. Perhaps the solution is to keep only the last yaml uploaded. 

2. Automatically update the `directory` value in t2wmlproject yaml
Perhaps I am using the project directory incorrectly. I copy a project directory under ~/.t2wml/storage,  then try to load this project directory copy. It seems that I have edit the `directory` value to be copy destination directory.
```
directory: /home/ktyao/ttt-projects/Region_b_2
```

**Comment by devowit** [comment]
Re 1: Yes, this is a known bug (#176 - although your report is better, I think I'll close mine), will get to it hopefully today.

re 2: unfortunately, there is no way around the need to change the directory manually for GUI use while we are still using the current server setup. if you are using the API to open the project file it does load the new directory and update the directory value. However, when using the server, there is no normal way (we checked) to get the actual file path instead of what is written in the file (other than the other option provided in the load window, for the user to manually paste in the folder path). 

This is not going to be a permanent situation-- we are going to be changing how the server is configured so we no longer have to deal with this kind of problem, that's the eventual goal of the electron installer. But t's a fairly extensive change already past the boundaries of a bug fix...

**Comment by devowit** [comment]
I have moved this to ready for testing on the basis of problem 1, which I think should now be resolved enough to work with. I haven't touched problem 2. 

The broader aesthetic issue of how yaml files are saved to the database (where multiple copies of a file get generated, each time you press apply) remains, but shouldn't be urgent (ie interfering with usage) and should be resolved in a natural way when we transition away from database to folder-based storage, therefore I think we can leave it for now despite the weirdness.

**Comment by kyao** [comment]
Problem 1 tested. It's working. 

I will move this back to To Do for problem 2.

**Comment by devowit** [comment]
very related to #187, should be resolved simultaneous to it being completed.

**Comment by devowit** [comment]
version 2.3.4
please close when tested ok

**Comment by kyao** [comment]
I could not get this to work with version 2.3.4.

I create a new project, and copy the files in the project directory to another directory. But, 

Open Project` does not seem to recognize the copied directory. 

Here is the zipped project directory.
[time.tar.gz](https://github.com/usc-isi-i2/t2wml/files/5197929/time.tar.gz)

**Comment by kyao** [comment]
On my Ubuntu system all files starting with `.` are hidden by default. I had to use `control-h` to toggle the display to show the `.t2wmlproj` file.

But, when I select that `.t2wmlproj` file I get this error:
![image](https://user-images.githubusercontent.com/1087657/92664830-e69ad600-f2b9-11ea-9e9d-67173bea6447.png)

**Comment by devowit** [comment]
can you do me a favor and send me the zip of the problem project folder? Will attempt to open on ubuntu

**Comment by kyao** [comment]
@devowit The problem is with the filepath separator on Linux. 
If I change this line:
https://github.com/usc-isi-i2/t2wml/blob/development/electron/src/main/menu.ts#L141
```
            const index = result.filePaths[0].lastIndexOf('\\');
```
to 
```
           const index = result.filePaths[0].lastIndexOf('/');
```
Then it works

**Comment by devowit** [comment]
I am moving the file line issue to its own, separate issue (#223) 
Therefore, closing this.
