### ISSUE TITLE
Annotation disappears, or connection to annotation file disappears

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#339]
this bug comes in more and less severe form.

less severe form: on a sheet that has both a yaml and annotation file, from the yaml file, press the annotation toggle. the sheet will switch to annotation mode but not to the existing annotation file, ie will be empty of colors. clicking on the annotation file bring us to the existing annotation file and can proceed as normal. proceeding to annotate in the empty-annotation will overwrite the existing annotation.

more severe form (can't reliably reproduce): some combination of factors when switching modes erases the annotation. the colors of the annotation DO show up-- but clicking a cell doesn't select that cell's block, instead the annotation menu pops up as if for a new selection. and indeed the auto-generated yaml is empty as if there is no annotation.

**Comment by g1eb** [comment]
In a somewhat related case, if there is a correct Yaml file but there are no annotations yet:
1. we fetch the mapping with `&mapping_type=Yaml`
2. the colors show up in output mode correctly

At that point switching to the annotation mode triggers a new GET request
1. we fetch the mapping with `&mapping_type=Annotation`
2. the previous entries are reset to [] because there are no annotations
3. the colors in output mode are not showing anymore

Possible fix would be to not overwrite the existing layers and entities with the empty ones when they are returned.
Alternatively we could return 404 for the mapping request in annotation mode with any annotations or annotations file.

**Comment by g1eb** [comment]
After a quick discussion with Pedro I learned that this behavior is correct albeit maybe a little confusing for the users.

When people switch from the custom made YAML file to the annotation files the colors should be reset in order to represent the current state of that annotation file (and if it's empty then there are no colors indeed).

That being said, if we are going to support multiple generated annotation files in annotation mode then we should disable the annotation mode toggle when users are viewing the custom YAML because of the ambiguity of which annotation file would be used when the users switch to the annotation mode.

**Comment by g1eb** [comment]
I've disabled the Annotation toggle button when the selected file is a YAML over on the `fix/annotation-toggle` branch

**Comment by devowit** [comment]
That is not a solution as it means there is no way for users to create an
annotation when there is a yaml.

**Comment by g1eb** [comment]
The idea was that the user would select a different type of file in the file tree.
Annotation toggle is only disabled when viewing the YAML file, you can try it in the `fix/annotation-toggle` branch.

You can click on the `annotations/<filename.csv>` to switch to enable annotations toggle.
![Screen Shot 2021-02-06 at 8 35 16 AM](https://user-images.githubusercontent.com/1916056/107124081-7dae8e80-6856-11eb-9f13-1bd32b5f8e69.png)

**Comment by devowit** [comment]
Once we have a properly functional file tree where it is possible to add an
annotation file not via the toggle I agree that getting rid of it for yaml
files is best. But until then we are stuck with the mediocre solution we
have now.

**Comment by szeke** [comment]
When the active YAML is a custom YAML, the annotation button is disabled because the YAML is not linked with an annotation. The user can select an annotation layer in the file tree, and there should be a link in the file tree to create a new annotation layer (in the figure about it would be below `canonical.yaml`)

**Comment by devowit** [comment]
i've merged the branch feature/right-click-menu to development. 
it gets rid of the annotation toggle when on a yaml file.
more importantly, it adds a right click menu to the file tree, for renaming, deleting, adding, removing, files. in particular it is possible to add annotation/yaml files from the file tree. 
if a sheet has a yaml file, you'll need to right click -> add annotation file to create an annotation for that sheet, since there's no more annotation toggle on yaml files.
however, for sheets with no mapping file at all, it is still possible to automatically and silently create an annotation file by switching to annotation mode from the toggle.

**Comment by g1eb** [comment]
> i've merged the branch feature/right-click-menu to development.

This merge introduced new typescript issues that should be cleaned up in development (or preferably on the feature branch before merging into development)

> it gets rid of the annotation toggle when on a yaml file.

I'm fine with [this](https://github.com/usc-isi-i2/t2wml/commit/b9cffcbbb3f7d7983bfbf3e6615465d198346957) solution but did you have a chance to look at the `fix/annotation-toggle` that I mentioned earlier?
