### ISSUE TITLE
Figure out how to track the window size to show the annotation menu

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/t2wml#348]

**Comment by zmbq** [comment]
We need to remove the annotationMenuPosition property from the components that have it.

**Comment by g1eb** [comment]
I've tried doing this with the main window in electron but it only updates once and we need to know the updated width every time users resize the window.

```
mainWindow.once('resize', () => {
  settings.updateSettingsFromWindow(mainWindow!);
});
```

**Comment by g1eb** [comment]
Ended up using `window.innerWidth` to get the window size in the annotation menu component.

Moved annotation menu window to the right of the screen so that it does not overlap any selections people are making.
Maybe for the output mode it's better that we show the errors in the menu right next to the cell so I left it as is for now.

Pushed to the `development` branch.
