### ISSUE TITLE
Adding a new annotation file does not select this annotaiton file

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/t2wml#366]
Rightclick on a sheet in the file tree, select Add a New Annotation File, fill the annotation file name and close the dialog. A new annotation file is created, but it's not selected. It should be selected, and the mode should change to annotation mode.

**Comment by g1eb** [comment]
Currently I can not create a new annotation file using right-click menu at all, these are the options in the right-click menu:

![Screen Shot 2021-02-12 at 8 22 07 PM](https://user-images.githubusercontent.com/1916056/107841500-37828f00-6d70-11eb-92e3-0c2acda39097.png)

**Comment by g1eb** [comment]
It turns out that the options of the right-click menu depend on _*exactly where*_ you click in the file tree 

Personally I'm not a fan of this kind of inconsistency, I would expect the menu to have the same options regardless of where I clicked in the file tree.

That being said, I understand that the created annotation files need to be nested under the correct sheet. Perhaps we could have a separate menu asking users which sheet this annotation file is for? (if there are multiple sheets) And/Or pre-select the sheet in question that was closest to the users click event location.
