### ISSUE TITLE
Multiple options in the annotation suggestion API

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#449]
We are getting multiple options from the annotation suggestion API endpoint and only using the first suggested option as the pre-selected option in the annotation menu.

Is there a reason for the multiple options being suggested? Is there a frontend implementation in the desktop app that supports multiple options shown in the annotation menu?

Example output from the `/api/annotation/suggest` endpoint:  
```
{
  "roles": [
    "mainSubject",
    "qualifier",
    "dependentVar"
  ],
  "types": [
    "string",
    "wikibaseitem"
  ],
  "children": {}, 
}
```

These suggestions are not conform the [annotation options dictionary](https://github.com/usc-isi-i2/t2wml/blob/development/electron/src/renderer/project/table/annotation-table/annotation-options.tsx) that we use to build the annotation form. Main subject does not have any type selections associated with it and if that's the suggestion (which is usually correct) then perhaps there shouldn't be any type suggestions? @szeke do you have any ideas/suggestions for this?

**Comment by zmbq** [comment]
The suggestion has multiple values because it's possible the suggestion is wrong. These are the likely values they user should see in the dropdown. 

⁣הורד את BlueMail עבור Android ​

ב-28 באפר׳ 2021, 06:36, ב-Gleb ***@***.***>, 06:36 כתב:

**Comment by szeke** [comment]
The suggestion API should return a single value for each menu based on what it thinks is the correct value

- role = item or property, then no more suggestions because the other menus are not shown
- role = qualifier, then offer suggestions for type, and if the suggested type is quantity, then the date, if the suggested type is date, then the precision, etc.
- role = variable, same think, offer suggestions for the other menus.

The suggestion API does not define the elements that appear in the menus. We have a static configuration of the dependencies between the menus. These dependencies are enforced in the front end, and should always be exactly the same, that is the **elements in the menu do no change** regardless of the suggestions, and are **always in the same order**.

The role of the suggestions is to pre-select the values in the menus.

**Comment by devowit** [comment]
this has been updated in development branch of t2wml-api (and in corresponding t2wml code)
it now returns:

{role: string, type?: string, children: {string key: string value}}, where children is an empty dictionary if no related fields are returned.

**Comment by g1eb** [comment]
Works like a charm! Thank you for updating it.
