### ISSUE TITLE
Property tag form truncated upon restore from t2wmlz file

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#623]
Property tag popup truncated if the session is restored from a t2wmlz file.

![image](https://user-images.githubusercontent.com/1087657/131567939-801a20ee-d308-4c1d-8a4e-e475cbbc9bf7.png)

T2WMLZ file:
[World_Education_Index_1629916288049.zip](https://github.com/usc-isi-i2/t2wml/files/7086535/World_Education_Index_1629916288049.zip)

**Comment by g1eb** [comment]
@kyao upon further inspection, this issue is related to [https://github.com/usc-isi-i2/t2wml/issues/604](https://github.com/usc-isi-i2/t2wml/issues/604)

We should really consider adding the tags directly to the qnode layer. Right now we have to do go and separately check each qnode, and if it does not have tags we have to go fetch those tags separately. This would be a much easier data structure to work with, leading to less render issues down the road. I'll add a workaround for now.

**Comment by devowit** [comment]
tags are returned with the qnode layer in commit 370cc586602 in branch causx-tags, I'm working on the remaining tag issues and then will merge into development
